Repository RichardTsibu76/AirBnB_clone_v3, pull requests merged in 2024-04, with the labels that each got.

#1 Code refactoring and impprovements
  .gitignore
  lazy_methods.py
  models/__init__.py
  models/engine/db_storage.py
  models/engine/file_storage.py
  requirements.txt
  tests/test_models/test_amenity.py
  tests/test_models/test_engine/test_db_storage.py
  tests/test_models/test_engine/test_file_storage.py
Labels: enhancement

#3 Add count and get methods to FileStorage and DBStorage classes
  models/__init__.py
  models/engine/db_storage.py
  models/engine/file_storage.py
  tests/test_models/test_engine/test_db_storage.py
  tests/test_models/test_engine/test_file_storage.py
Labels: enhancement

#6 Refactor get method in FileStorage class and add error handling for 404 page not found
  api/v1/app.py
  models/engine/file_storage.py
Labels: bug, enhancement

#8 Add Flask development server scripts and API endpoints for states
  api/v1/app.py
  api/v1/views/__init__.py
  api/v1/views/states.py
  db-flask
  fs-flask
  models/engine/db_storage.py
  models/engine/file_storage.py
Labels: enhancement

#11 Add API endpoints for managing cities in the Flask API
  api/v1/app.py
  api/v1/views/__init__.py
  api/v1/views/cities.py
Labels: enhancement

#10 Update handle_state function signature in states.py
  api/v1/views/states.py
  db-flask
  fs-flask
Labels: bug

#9 Refactor tests to use string formatting instead of f-strings
  tests/test_models/test_engine/test_db_storage.py
  tests/test_models/test_engine/test_file_storage.py
Labels: bug, enhancement

#15 Fix request.get_json() usage and add empty line
  api/v1/views/states.py
  lazy_methods.py
Labels: bug

#14 New view for amenity
  api/v1/views/__init__.py
  api/v1/views/amenities.py
  api/v1/views/cities.py
Labels: enhancement

#16 Update import statements and add new view for cities in API v1
  api/v1/views/__init__.py
  api/v1/views/cities.py
Labels: bug, enhancement

#18 Refactor API view functions to handle JSON data more efficiently
  api/v1/views/amenities.py
  api/v1/views/cities.py
  api/v1/views/states.py
  api/v1/views/users.py
Labels: enhancement
